# Container does not perform any initialization aside from importing env-vars from `confd`.
# Users are expected to manually set up their site using a combination of the following:
# - Makefile targets
# - composer requires / install
# - Drush commands
# - Manual changes to the codebase directory
version: "3.7"
networks:
  default:
    internal: true
  gateway:
    external:
      name: gateway
volumes:
  drupal-sites-data:
  solr-data:
services:
  drupal:
    image: ${REPOSITORY:-islandora}/drupal:${TAG:-latest}
    volumes:
      - ./codebase:/var/www/drupal:delegated
      - drupal-sites-data:/var/www/drupal/web/sites/default/files
      - solr-data:/opt/solr/server/solr
    depends_on:
      # Requires a the very minimum a database.
      - ${DRUPAL_DATABASE_SERVICE}
    secrets:
      - source: sp_key
      - source: sp_cert
      - source: sp_hashing_salt
      - source: sp_admin_pw
  # Extends docker-compose.solr.yml
  solr:
    volumes:
      # On a production site you may not want to take this approach but instead refer to each of the cores
      # data directories specifically and maintain the configuration as part of a customized image, where
      # in your configuration is Solr managed under source control somewhere.
      - solr-data:/opt/solr/server/solr

secrets:
  sp_key:
    file: ./secrets/sp/sp-key.pem
  sp_cert:
    file: ./secrets/sp/sp-cert.pem
  sp_hashing_salt:
    file: ./secrets/sp/sp-hashing-salt
  sp_admin_pw:
    file: ./secrets/sp/sp-admin-pw
